version: "3.4"

services:
  snakeia-server:
    image: eliastik/snakeia-server:latest
    container_name: snakeia-server
    restart: unless-stopped
    # uncomment to build the image
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./config/default.json:/home/snakeia-server/server/config/default.json
      # - ./config/local.json:/home/snakeia-server/server/config/local.json
      - ./error.log:/home/snakeia-server/server/logs/error.log
      - ./server.log:/home/snakeia-server/server/logs/server.log
    ports:
      - "3000:3000"